# Generated by Django 6.1 on 2026-08-06 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='workspace',
            table='workspace',
        ),
        migrations.AlterModelTable(
            name='workspacemember',
            table='workspace_member',
        ),
    ]
