# Generated by Django 5.2.3 on 2026-08-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_table'),
        ('workspaces', '0002_alter_workspace_table_alter_workspacemember_table'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workspacemember',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='workspacemember',
            constraint=models.UniqueConstraint(fields=('workspace', 'user'), name='unique_workspace_member'),
        ),
    ]
