# Generated by Django 6.1 on 2026-08-06 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='document',
            table='document',
        ),
        migrations.AlterModelTable(
            name='documentversion',
            table='document_version',
        ),
    ]
