# Generated by Django 5.2.3 on 2026-08-14 18:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_table_alter_documentversion_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentversion',
            old_name='saved_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='documentversion',
            old_name='saved_by',
            new_name='created_by',
        ),
        migrations.RemoveField(
            model_name='document',
            name='content',
        ),
        migrations.AddField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
